// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gf-app-demo/app/model/internal"
)

// Test is the golang structure for table test.
type Test internal.Test

// Fill with you ideas below.
