// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Test is the golang structure for table test.
type Test struct {
	Id   int    `orm:"id,primary" json:"id"`   //
	Name string `orm:"name"       json:"name"` //
	Sex  int    `orm:"sex"        json:"sex"`  //
}
