# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "logs/serve"

# Logger.
[logger]
    Path        = "logs/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    [[database.default]]
        link  = "mysql:root:zhh123@tcp(127.0.0.1:3306)/test?loc=Local"
        debug = true
    # Database logger.
    [database.logger]
        Path   = "logs/sql"
        Level  = "all"
        Stdout = true


[redis]
    default = "127.0.0.1:6379,0?maxIdle=5&maxActive=100&idleTimeout=600"
    cache   = "127.0.0.1:6379,1,123456?idleTimeout=600"


[gfcli]
    [[gfcli.gen.model]]
            link   = "mysql:root:zhh123@tcp(127.0.0.1:3306)/test"
            tables = "test"

    [[gfcli.gen.dao]]
        link   = "mysql:root:zhh123@tcp(127.0.0.1:3306)/test"
        tables = "test"